#!/bin/bash

psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOF
ALTER USER $POSTGRES_USER CREATEDB;
GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
CREATE DATABASE $DB_DATABASE
EOF
